import Navbar from '@/components/layout/navbar';
import { NextUIProviders } from '@/components/nextui-providers';
import Collections from '@/components/search/collections';
import FilterList from '@/components/search/filter';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode, Suspense } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" className={inter.className}>
			<body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
				<NextUIProviders>
					<Navbar />
					{/* <Suspense> */}
					{/* <main>{children}</main> */}
					{/* </Suspense> */}
					<Suspense>
						<div className="flex w-full justify-center pt-16">
							<div className="flex w-[1240px]">
								<div className="flex w-full flex-col gap-8 pb-4 text-black dark:text-white md:flex-row">
									<div className="order-first w-full flex-none md:max-w-[125px]">
										<Collections />
									</div>
									<div className="order-last min-h-screen w-full md:order-none">{children}</div>
									<div className="order-none flex-none md:order-last md:w-[125px]">
										<FilterList list={[]} title="Sort by" display="end" />
									</div>
								</div>
							</div>
						</div>
						{/* <Footer /> */}
					</Suspense>
				</NextUIProviders>
			</body>
		</html>
	);
}
