import HomePageHead from '@/components/layout/home-page-head';
import Navbar from '@/components/layout/navbar';
import { NextUIProviders } from '@/components/nextui-providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import { ReactNode, Suspense } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" className={inter.className}>
			<Script src="/custom.js"></Script>
			<body className="touch-pan-y bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
				<NextUIProviders>
					<Navbar />
					<Suspense>
						<div className="flex flex-col justify-center bg-neutral-50">
							<HomePageHead />
							<div className="flex max-w-[1240px] p-4">
								<div className="flex w-full flex-col gap-4 text-black">
									<div className="order-last min-h-screen w-full md:order-none">{children}</div>
								</div>
							</div>
						</div>
					</Suspense>
				</NextUIProviders>
			</body>
		</html>
	);
}
